### ISSUE TITLE
音乐播放问题

### ISSUE THREAD

**Issue by happytraveller-alone** [TriDiamond/hexo-theme-obsidian#101]
版本更行后，音乐无法进行播放；不同文章下是否可以搭配不同的音乐，经过测试后，只能使用默认音乐

**Comment by TriDiamond** [comment]
是可以使用不同音乐的，但是要在meta-data哪里配置，就是md文档的头部。你是尝试过，不行吗？

你说的版本更新，是hexo的新版本还是？

**Comment by happytraveller-alone** [comment]
已经运用本地的音乐文件进行了尝试，更新选择的是hexo-theme-obsidian的最新版本，本地初始化查看音乐播放无声音，已排除电脑的硬件和音乐大小问题。

**Comment by happytraveller-alone** [comment]
在Markdown的文档开头表明音乐引用，如下：
---
title: 第一次见面
date: 2020-06-08 18:00:00
categories: test 
tags: report 
cover: img/welcome-cover.jpg
mp3: statics/Revolve(R-mix).mp3
preview: 20
---
对应public/statics文件下音乐文件

**Comment by TriDiamond** [comment]
@happytraveller-alone 音乐文件需要放到这个地方才行哈

![image](https://user-images.githubusercontent.com/24708758/87735709-dfe76980-c808-11ea-8098-90d6e61cded8.png)

**Comment by happytraveller-alone** [comment]
音乐只能调用默认音乐，调用Stacics里的音乐文件，无法进行播放。

**Comment by happytraveller-alone** [comment]
问题已经解决，采用调取与Markdown文档同名文件夹下的音乐文件的方法可以进行音乐播放。
