### ISSUE TITLE
关于文章阅读量的问题

### ISSUE THREAD

**Issue by JaydenChang** [TriDiamond/hexo-theme-obsidian#114]
大一小白，没学js，前几天刚搭博客。使用主题时遇到些问题：
使用valine的文章浏览量统计模块，从主页点进页面后统计量不会更新，需要刷新帖子的页面统计量才会更新；
使用不蒜子模块，虽然点进去统计量会更新，但是统计的是总访问量，不是每篇文章各自的阅读量，然后我也试过同时打开valine和不蒜子，这个情况下默认统计模块是不蒜子的，我也试过关闭valine的visitor，然后每一篇帖子的阅读数消失了。
现在的问题主要是想使用valine的评论系统和不蒜子的统计功能，无奈学识尚浅，不能自己解决，麻烦作者能指点我一下，有劳了

**Comment by TriDiamond** [comment]
@JaydenChang 主题目前是不支持 Valine 和不蒜子一起使用，所以才会有这个问题。在接下来的 2.x 重构版本，我会考虑一下这个问题的。谢谢你的支持。
