### ISSUE TITLE
页面CSS渲染之前的问题

### ISSUE THREAD

**Issue by ftitreefly** [TriDiamond/hexo-theme-obsidian#117]
网速慢的时候，首页加载会推迟到5秒以上，甚至更久，这时网页显示着已经加载的无css样式的Html内容。

loading动画的UI没有及时启动之前会有几秒处女座难以忍受的页面状态。
尝试在head添加style设置背景为黑色，减少视觉突变差异，效果一般。

有没有什么思路可以让页面加载即刻隐藏html信息直到css渲染达到最佳效果，或者尽可能减少无css样式的Html内容显示时间？

**Comment by TriDiamond** [comment]
这个问题，我在重构的时候考虑到了，这次的2.x重构将会使用 Vue3，一切都会好起来了。
