### ISSUE TITLE
网页标题不生效

### ISSUE THREAD

**Issue by IsaacRWangPhysics** [TriDiamond/hexo-theme-obsidian#118]
在hexo下的_config.yml里设置了title，author。hexo g -d之后进入页面，没有看到标题。我原计划是将左上角的“三钻”替换为我自己的标题。请问应该如何操作？

**Comment by TriDiamond** [comment]
右上角的三钻是一个图片，需要在 images 里面去替换图片即可，那个名字并不是在 config 里面去替换的哈。@IsaacRWangPhysics

**Comment by TriDiamond** [comment]
Long time no reply, will close this comment for now. Please reopen if the problem still exist.
长时间没有恢复，先关闭此 bug，如果问题还是存在，请新开 isssue 询问。
