### ISSUE TITLE
请问三·钻图片 能否提供修改替换 可自定义

### ISSUE THREAD

**Issue by ci666** [TriDiamond/hexo-theme-obsidian#122]
主页的这个地方 试过删除`obsidian/source/img/logo.png` 主页的三·钻 还会显示

![image](https://user-images.githubusercontent.com/20944512/111099371-58611e80-8580-11eb-931b-91b0b5b24d34.png)

还有文章里面的 John Doe
![image](https://user-images.githubusercontent.com/20944512/111099430-7890dd80-8580-11eb-96c8-05abafdec2e4.png)

页尾保留版权这个无所谓，但这几个地方还是希望可以自定义，谢谢大佬

**Comment by entireyu** [comment]
文章里面的名字可以通过hexo根目录下的_config.yml 里面的 author 更改呀，还有作者的头像和logo可以通过obsidian下的配置文件的avatar和favicon进行更改，三钻那两个字可以直接替换themes\obsidian\source\css 底下的css文件改掉背景

**Comment by ci666** [comment]
@entireyu 谢谢哥
三钻那两个字可以直接替换themes\obsidian\source\css 底下的css文件改掉背景 这个我还是没有找到
![image](https://user-images.githubusercontent.com/20944512/111141555-a72da900-85be-11eb-8867-b6458d722a10.png)

**Comment by ci666** [comment]
找到了 明白 谢谢！
