### ISSUE TITLE
Directory expands and focus shift

### ISSUE THREAD

**Issue by Sicmatr1x** [TriDiamond/hexo-theme-obsidian#13]
If your article has three levels of subdirectories and a large number of subdirectories, you may not be able to select subdirectories.

![2019-11-01 17_02_04-Clean Code - Sicmatr1x](https://user-images.githubusercontent.com/26240752/68014158-b2ce4780-fcc9-11e9-92f8-d8fb1c4d6a0d.png)

In fact, your mouse focus will be a little higher than the actual mouse position.You can see this in the text at the top, where the CSS style is thickened because it has been brought into focus.

In this example, if you click the left button of mouse you will go to `10. 类`.

In another example, you don't even need the cursor on any of the titles.

![2019-11-01 17_10_00-Oracle PL - Sicmatr1x](https://user-images.githubusercontent.com/26240752/68014450-9bdc2500-fcca-11e9-91db-ccb98964995b.png)

**Comment by TriDiamond** [comment]
I have tried it myself the clickable area surely has some glitch space, which make clicking a bit inaccurate. I will fix this asap. Thanks for your feedback!

**Comment by TriDiamond** [comment]
Fixed this issue on [v1.3.5](https://github.com/TriDiamond/hexo-theme-obsidian/releases/tag/v1.3.5)
