### ISSUE TITLE
音乐插件无法加载

### ISSUE THREAD

**Issue by binscor** [TriDiamond/hexo-theme-obsidian#150]
:4000/src/aplayer/dist/APlayer.min.js，
:4000/src/js/Meting.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
我想问一下，不知道是不是hexo版本的原因，这两个JS根本不在这两个目录下，导致音乐插件无法加载，我只能手动把代码里面引用这两个文件的地址改掉

**Comment by binscor** [comment]
生成之后整个aplayer文件在跟目录底下，主题配置文件里面  statics/chengdu.mp3，这个目录也不存在呢，我的hexo版本是3.9.0

**Comment by kcn3388** [comment]
请截取完整报错，包括报错行数
