### ISSUE TITLE
请问“关于我”页面如何生成

### ISSUE THREAD

**Issue by aigooman** [TriDiamond/hexo-theme-obsidian#16]
如题，请问像示例网站中的about页面应当如何生成？

**Comment by TriDiamond** [comment]
直接用Hexo的命令生成新的页面就可以了。

```bash
hexo new page whoami
```

**Comment by aigooman** [comment]
感谢回复，我想请教如何把style放到markdown中？正常md解析出来的标题是黑色的。[您的主页](https://tridiamond.me/whoami/)的md源文件能否分享呢？再次感谢~

**Comment by TriDiamond** [comment]
我的关于页面的md就是这样的。你可以参考一下

https://raw.githubusercontent.com/TriDiamond/TriDiamondBlog/master/source/whoami/index.md

**Comment by aigooman** [comment]
学到了，感谢~

**Comment by born198x** [comment]
> 学到了，感谢~



> 我的关于页面的md就是这样的。你可以参考一下
> 
> https://raw.githubusercontent.com/TriDiamond/TriDiamondBlog/master/source/whoami/index.md

最新版的whoami 分享下呗

**Comment by TriDiamond** [comment]
@born198x 最新的那个目前还没有提交代码。过几天我提交上来去吧。

**Comment by wxlyz1314** [comment]
你好，上面你的关于页面的md链接打不开，能否重发一下，因为一般的md解析出来是黑色的，需要借鉴，谢谢
