### ISSUE TITLE
主题太棒了！有没有添加搜索功能的计划

### ISSUE THREAD

**Issue by EwdAger** [TriDiamond/hexo-theme-obsidian#18]
这个主题太出众了~感觉唯一美中不足就是还没添加搜索功能了

**Comment by TriDiamond** [comment]
谢谢你的支持，搜索功能是在我的todo里面的。下一个版本我先重写一下archives的页面，然后就是加入搜索功能。

**Comment by TriDiamond** [comment]
@EwdAger 搜索功能上线了，请更新到版本[v1.4.2](https://github.com/TriDiamond/hexo-theme-obsidian/releases/tag/v1.4.2)
