### ISSUE TITLE
关于部分模块显示不正确的问题(Nodejs版本)

### ISSUE THREAD

**Issue by wuyuansushen** [TriDiamond/hexo-theme-obsidian#19]
请问这个项目是基于哪一版的Node.js呢，我找了半天也没找到对应版本，下了
`node -v`

> v12.13.0

会出现部分显示错误

**Comment by TriDiamond** [comment]
> 请问这个项目是基于哪一版的Node.js呢，我找了半天也没找到对应版本，下了
> `node -v`
> 
> > v12.13.0
> 
> 会出现部分显示错误

我用的是v10.16.0

**Comment by wuyuansushen** [comment]
> > 请问这个项目是基于哪一版的Node.js呢，我找了半天也没找到对应版本，下了
> > `node -v`
> > > v12.13.0
> > 
> > 
> > 会出现部分显示错误
> 
> 我用的是v10.16.0，可以描述一下是那些部分/模块显示不全呢？

谢谢，我去试试，一天白干了，模块显示不全是那个底下的蓝条变成只有半截，就那个“艺术xxx”有两个短话来回滚动的
准确来说是
_config.yml文件中
`# Website slogans
descriptionOne: "Think like an artist, develop like an artisan"
descriptionTwo: "艺术家思维去思考问题，工匠创造精神去开发"`
这个部分

**Comment by TriDiamond** [comment]
> > > 请问这个项目是基于哪一版的Node.js呢，我找了半天也没找到对应版本，下了
> > > `node -v`
> > > > v12.13.0
> > > 
> > > 
> > > 会出现部分显示错误
> > 
> > 
> > 我用的是v10.16.0，可以描述一下是那些部分/模块显示不全呢？
> 
> 谢谢，我去试试，一天白干了，模块显示不全是那个底下的蓝条变成只有半截，就那个“艺术xxx”有两个短话来回滚动的
> 准确来说是
> _config.yml文件中
> `# Website slogans descriptionOne: "Think like an artist, develop like an artisan" descriptionTwo: "艺术家思维去思考问题，工匠创造精神去开发"`
> 这个部分

那个部分呢，如果是屏幕宽度变化触发到响应css，是会有点问题的。但是如果你刷新一下页面就会触发js自动运算了。看看是不是这个问题，如果不是，那就是node.js版本问题。

**Comment by wuyuansushen** [comment]
> > > > 请问这个项目是基于哪一版的Node.js呢，我找了半天也没找到对应版本，下了
> > > > `node -v`
> > > > > v12.13.0
> > > > 
> > > > 
> > > > 会出现部分显示错误
> > > 
> > > 
> > > 我用的是v10.16.0，可以描述一下是那些部分/模块显示不全呢？
> > 
> > 
> > 谢谢，我去试试，一天白干了，模块显示不全是那个底下的蓝条变成只有半截，就那个“艺术xxx”有两个短话来回滚动的
> > 准确来说是
> > _config.yml文件中
> > `# Website slogans descriptionOne: "Think like an artist, develop like an artisan" descriptionTwo: "艺术家思维去思考问题，工匠创造精神去开发"`
> > 这个部分
> 
> 那个部分呢，如果是屏幕宽度变化触发到响应css，是会有点问题的。但是如果你刷新一下页面就会触发js自动运算了。看看是不是这个问题，如果不是，那就是node.js版本问题。

刷新过好多次了，还是不行

**Comment by TriDiamond** [comment]
@wuyuansushen 那就是node.js版本兼容问题，这个很有可能是hexo自身的兼容问题。你试试换下来吧。

**Comment by wuyuansushen** [comment]
@TriDiamond 好，我換下來看看，用的是Firefox Develop Editer，就藍色的那個火狐瀏覽器開發者版本進行測試，不用懷疑，因爲我用同一個瀏覽器打開你的那個.me域名的網站是顯示正常的

**Comment by TriDiamond** [comment]
@wuyuansushen 你的问题是否已经解决了？

**Comment by wuyuansushen** [comment]
@TriDiamond 不好意思d(ŐдŐ๑)今天體測1000米累死了，沒有空測試，我明天再試試吧，謝謝關心
