### ISSUE TITLE
报个bug，提个建议

### ISSUE THREAD

**Issue by zam90** [TriDiamond/hexo-theme-obsidian#20]
您好，很喜欢你的这个主题，做的很好看，更新也很快。感谢你提供给我们这么好的主题！
1.4.0版本有个小问题：目录文字太长会超出目录显示范围，文字悬空。望下个版本修复！
一个小建议：添加个文章搜索功能吧~文章太多找不到了

**Comment by TriDiamond** [comment]
@zam90 好的，我这边看一下这个问题，会在1.4.1版本去修复。还有搜索的功能已经安排了。最近几个版本就会加入进入。谢谢你的支持！❤️

**Comment by TriDiamond** [comment]
@zam90 
![image](https://user-images.githubusercontent.com/24708758/68528613-06770b80-0330-11ea-9e7c-cfc15c529cc0.png)

我这边用了1.4.0版本的看过，我有做超出长度的处理的。你确定你用的是1.4.0？你升级后有没有重新生成文件？

用一下命令重新生成：
```bash
hexo clean && hexo g
```

**Comment by zam90** [comment]
![1a1183ea9f1a2bce0cba646811049fb](https://user-images.githubusercontent.com/44944085/68683101-2fea9e00-05a1-11ea-9ba6-f34a706a6ded.png)
![c8ec03ee4b53e3321b389bd3c3b8acc](https://user-images.githubusercontent.com/44944085/68683103-2fea9e00-05a1-11ea-8bbc-311e514a3a62.png)
您好，我使用的是1.4.0版本，也做了clean处理....还是有些问题

**Comment by zam90** [comment]
应该是多级菜单引起的问题

**Comment by TriDiamond** [comment]
那我知道是什么问题了，我会处理一下这种多层级的。不过要想想怎么布局的问题了。

**Comment by zam90** [comment]
好的 非常感谢

**Comment by TriDiamond** [comment]
@zam90 
这个问题已经在[版本1.4.3](https://github.com/TriDiamond/hexo-theme-obsidian/releases/tag/v1.4.3)里面解决了。解决版本就是现在目录只显示到第三级。其实吧基本到第三级就够了。目前是这么解决这个样式问题哈。如果你有什么更好的意见也可以给我提以下哦！谢谢！

**Comment by zam90** [comment]
好的 已收到 今天我更新主题测试一下 感谢你哦～
