### ISSUE TITLE
如何把顶栏的宽度缩短一丢丢？

### ISSUE THREAD

**Issue by Bugatti100Peagle** [TriDiamond/hexo-theme-obsidian#22]
顶栏太宽，把下面的内容盖住了一部分。

![](http://newblogimg.oss-cn-beijing.aliyuncs.com/blog/20191109/152540735.png)

![](http://newblogimg.oss-cn-beijing.aliyuncs.com/blog/20191109/152726041.png)

**Comment by TriDiamond** [comment]
@Bugatti100Peagle 这个页面的UI我重新设计了，你可以拉一下最新的主题代码哈。
