### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by Herzeleid-k** [TriDiamond/hexo-theme-obsidian#25]
您好，我在使用您的主题，特别喜欢你主题的峰哥，这是我在使用您的主题的时候遇到的几个问题，想向您请教一下：
1、我创建好了目录页和标签页，但是目录页中的目录关键字点击后会出现404 无法找到的页面，目录页的相关信息是需要自己来填写吗？并不是自动生成？
2、从标签页和目录页返回首页的时候，点击返回按钮，会弹出新的页面，浏览器地址里显示about:blank#blocked，这个是因为我搭建的原因吗？
谢谢您了！

**Comment by zam90** [comment]
分类页、标签页、归档页应该是创建完成之后留空就可以了，不用添加任何东西
创建完成后点击关键字404的话，你执行一下`hexo c`然后再执行`hexo g`试一下，我觉得应该是生成博客的问题，或者是github page没有刷新，你多刷新几次试一下

**Comment by zam90** [comment]
从标签页和归档页点击返回按钮应该不会出现新弹窗的，而且浏览器地址应该是你的首页
这个应该是你博客搭建的问题，我暂时还没遇到过这种情况

**Comment by TriDiamond** [comment]
@Herzeleid-k 是的，是你搭建的问题。具体问什么，你试试 @zam90 说的方式。重新生成文件，还有你需要用hexo server来启动网页的哈。虽然说hexo会生成静态index.html。但是是不能直接打开的。是要有服务器辅助打开的哈。hexo server 之后需要访问localhost:4000

**Comment by Herzeleid-k** [comment]
好的，谢谢你们，我在重新搭建是一次试试看。

**Comment by yuebaiqinghui** [comment]
我遇到了一样的问题，属性上有target="_blank",所以会打开新的空白页。。然后我现在也没找到解决方案，修改了ejs但构建出来还是会有这个属性

**Comment by AI-Python-QI** [comment]
> 我遇到了一样的问题，属性上有target="_blank",所以会打开新的空白页。。然后我现在也没找到解决方案，修改了ejs但构建出来还是会有这个属性

这个问题issue有人解决了，就是把config配置的
external_link:
  enable: false # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
这个功能由true改为false 就可以解决啦

**Comment by TriDiamond** [comment]
Duplicate of #29
