### ISSUE TITLE
website slogans显示不全

### ISSUE THREAD

**Issue by buxcon** [TriDiamond/hexo-theme-obsidian#26]
看您网站的slogan效果是在贯穿屏幕左右的一个条带上显示，但是[我的网站](https://buxcon.io)显示的不一样，只在左边有一小块蓝底，字数比较多的话就显示不全

**Comment by TriDiamond** [comment]
![image](https://user-images.githubusercontent.com/24708758/68852030-08671300-0712-11ea-8e30-f1e9f849ee9e.png)

我看了一下，我看到是显示全的。你是不是打开了调试模式，然后网页宽度变化了？如果是变化了刷新一下页面就好了。因为里面有一个响应式css是无法完全自动适应宽度。有js辅助计算的哈。

**Comment by buxcon** [comment]
我自己又试了下，应该是我电脑设置的dpi的关系，设的150%所以网页也放大了...

**Comment by TriDiamond** [comment]
@buxcon 这个也优点意思哦，我还真没有考虑到放大的兼容问题。这个我可以在后面进行优化。
