### ISSUE TITLE
随机封面功能

### ISSUE THREAD

**Issue by EwdAger** [TriDiamond/hexo-theme-obsidian#27]
有没有考虑随机使用文章页封面的功能，感觉默认只使用一张默认封面和默认文章封面有点少。而每篇文章都添加一个cover又有点不太合适。

**Comment by Sicmatr1x** [comment]
我试过每篇文章添加一个cover，可能会导致加载首页的时候因为需要加载的图片太多而速度十分缓慢

**Comment by Bugatti100Peagle** [comment]
那能否让这个加载的图片的链接变化，有点像每次打开Win10登录界面的风景图片一样，或者把Cover接到bing每日图片上这样？

**Comment by yansheng836** [comment]
有兴趣可以了解下Bing的每日壁纸,API:<https://api.uixsj.cn/bing/bing.php>，直接访问即可返回一张壁纸，日更。在网页中使用可参考下面的代码：

```html
<img src="https://api.uixsj.cn/bing/bing.php" width="auto" height="auto" alt="Bing每日图片">
```

**Comment by TriDiamond** [comment]
使用外部的接口倒是可以的，但是如果是自己放入图片没有CDN的支持，确实会很慢的。
