### ISSUE TITLE
css样式混乱

### ISSUE THREAD

**Issue by smile0304** [TriDiamond/hexo-theme-obsidian#3]
我这个字数为150， css样式会乱掉

是不是跟屏幕大小又问题？ 我这个屏幕分辨率时1920x1080

![image](https://user-images.githubusercontent.com/20963266/67159883-0ca34900-f37d-11e9-85d5-2e43bb437aaf.png)

**Comment by TriDiamond** [comment]
你要控制好文章的预览字数，因为我没有控制死高度。这个其实我可以优化一下的。我周一优化一下这个样式。控制好最大高度就好了。谢谢持续支持！💪💪💪

**Comment by TriDiamond** [comment]
我对首页的第一个文章的高度做了处理, 现在会根据文章实际的高度来相应. 
请拉去最新主题的master代码. 版本1.3.2
谢谢你的反馈!
