### ISSUE TITLE
博客中图片下面出现多个标题

### ISSUE THREAD

**Issue by Knlvre** [TriDiamond/hexo-theme-obsidian#31]
比如语法内图片是    !【标题】(图片地址)
然后博客上出现就是

![标题](https://raw.githubusercontent.com/Knlvre/knlvre.github.io/master/img/hexo%2Bgit/bug.png)

**Comment by Knlvre** [comment]
发现原因了：同一篇文章内图片标题一样会出现这种情况

**Comment by TriDiamond** [comment]
@Knlvre 对这个问题还没有去优化，先避免多个图用同一个名字。

**Comment by Knlvre** [comment]
好的，谢谢！很喜欢你的主题，是我见过最棒的主题！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Guo Xiang"<notifications@github.com&gt;; 
发送时间: 2019年11月30日(星期六) 中午1:45
收件人: "TriDiamond/hexo-theme-obsidian"<hexo-theme-obsidian@noreply.github.com&gt;; 
抄送: "黄书葳"<240375426@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [TriDiamond/hexo-theme-obsidian] 博客中图片下面出现多个标题 (#31)




@Knlvre 对这个问题还没有去优化，先避免多个图用同一个名字。

**Comment by TriDiamond** [comment]
@Knlvre 谢谢你的支持

**Comment by shirukai** [comment]
我也遇到同样的问题，我的图片一般都不附带标题，所以会出现图片下面有好多行""，看了您的代码，代码位置：source/js/obsidian.js，修改成如下内容就没有问题了：
```
/**
 * Buidling the caption html in an aritle
 */
function buildImgCaption() {
  var images = $('.content').find('img');

  images.each(function () {
    var caption = $(this).attr('alt');
    if (caption!=="" && caption !==undefined){
      $(this).parent().append('<p class="image-caption">"' + caption + '"</p>');
    }
  });
}
```

**Comment by TriDiamond** [comment]
已经在版本1.4.4 修复了这个问题。谢谢大家的支持！
