### ISSUE TITLE
难道各位大佬没有发现阅读数展示有问题？第一次进文章详情 阅读数 直接显示100万 没人遇到么？

### ISSUE THREAD

**Issue by born198x** [TriDiamond/hexo-theme-obsidian#32]
难道各位大佬没有发现阅读数展示有问题？第一次进文章详情 阅读数 直接显示100万 没人遇到么，必须我手动刷新下 这是个BUG吧？如下图：

![image](https://user-images.githubusercontent.com/57509061/69710789-f71efd00-113a-11ea-8b74-ab48f4f0da37.png)

**Comment by Fenco-Han** [comment]
born198x
        
        我们这边好像没有这个BUG
      
2019-11-27
| |
fenco_han
|
|
fenco_han@163.com
|
签名由网易邮箱大师定制
在2019年11月27日 17:26，born198x<notifications@github.com> 写道：

难道各位大佬没有发现阅读数展示有问题？第一次进文章详情 阅读数 直接显示100万 没人遇到么，必须我手动刷新下 这是个BUG吧？如下图：

**Comment by born198x** [comment]
@Fenco-Han 啥情况 难道只有我这有...

**Comment by born198x** [comment]
@TriDiamond 大佬 能帮忙确认下么？我打算再升级到最新版本试试

**Comment by TriDiamond** [comment]
你用的是valine的阅读量吧？

**Comment by born198x** [comment]
@TriDiamond 对对 就是那个 valine 不会就 valine 有问题吧 因为我看它是国内的 应该网络会好点

**Comment by TriDiamond** [comment]
@born198x  你按官方文档配置好了是吗？你现在看到的错误查看数是在那个环境看到的？是你的本地环境还是线上环境？

**Comment by EwdAger** [comment]
使用valine的阅读量在线上环境点击文章名进入文章页阅读量是正常的，但是点击查看全文会直接显示阅读量1000000

**Comment by EwdAger** [comment]
> @born198x 你按官方文档配置好了是吗？你现在看到的错误查看数是在那个环境看到的？是你的本地环境还是线上环境？
使用valine的阅读量在线上环境点击文章名进入文章页阅读量是正常的，但是点击查看全文会直接显示阅读量1000000

**Comment by EwdAger** [comment]
使用valine的阅读量在线上环境点击文章名进入文章页阅读量是正常的，但是点击查看全文会直接显示阅读量1000000 @TriDiamond

**Comment by pangjian** [comment]
这是因为valine的阅读量, 默认值写的是1000000 
[比如这个代码](https://github.com/TriDiamond/hexo-theme-obsidian/blob/master/layout/_partial/screen.ejs#L79)
加载成功valine的真实数值以后才会改变.
我个人觉得默认写成-会不会好一点, 我看busuanzi的默认值是0

**Comment by born198x** [comment]
> @born198x 你按官方文档配置好了是吗？你现在看到的错误查看数是在那个环境看到的？是你的本地环境还是线上环境？

妥妥的线上环境！！！

**Comment by wxlyz1314** [comment]
你好我同样遇到该问题，线上环境第一次点击进入是100万，需要手动刷新才正常
![image.png](https://i.loli.net/2020/01/06/eMrAOibGVDHLKu7.png)
