### ISSUE TITLE
能加入mermaid插件吗

### ISSUE THREAD

**Issue by lioliy** [TriDiamond/hexo-theme-obsidian#39]
我手动添加了mermaid这个插件发现不能自动刷新（从首页转到正文），应该是动态网页吧，必须手动刷新才能有效果。

**Comment by TriDiamond** [comment]
对的，因为详情是移步加载的内容，所有编译需要在jquery里面加入触发编译才行哦。

**Comment by hekuzhengfeng** [comment]
如何在jquery里加入触发编译？可以在后续更新中加好么
