### ISSUE TITLE
初次初始化显示 htmlTruncate is not defined

### ISSUE THREAD

**Issue by windows99** [TriDiamond/hexo-theme-obsidian#40]
代码是 git clone 克隆到项目中的，在更改了主题后，重新渲染，就出了以下的问题！
![image](https://user-images.githubusercontent.com/34727157/71569617-53df5000-2b0b-11ea-96e5-64ee1f39774c.png)
奈何 ejs 还没太熟练，只好先提个问题了！

**Comment by TriDiamond** [comment]
请问你拉的是不是master的分支呢？

**Comment by windows99** [comment]
> 请问你拉的是不是master的分支呢？
是的，
![image](https://user-images.githubusercontent.com/34727157/71572084-7461d700-2b18-11ea-8289-6c163f1c3bbd.png)
克隆的这个图片的地址

**Comment by windows99** [comment]
问题已解决，需要在hexo根目录安装hexo-html-truncate依赖。文档并没有看到有提及到，不知道是在某些地方我没注意到还是没有描述，希望作者大人可以确认下!

**Comment by TriDiamond** [comment]
> 问题已解决，需要在hexo根目录安装hexo-html-truncate依赖。文档并没有看到有提及到，不知道是在某些地方我没注意到还是没有描述，希望作者大人可以确认下!

我记得我是写到了包里面的，不需要另外安装的。不过能解决就好。我后面会再确认一遍。

**Comment by peguine** [comment]
同样问题，试了N遍， 生成的首页是空白，安装hexo-html-truncate就好了。。。
