### ISSUE TITLE
question

### ISSUE THREAD

**Issue by fool-cats** [TriDiamond/hexo-theme-obsidian#48]
请问我部署完后博客全白屏的，不是404要怎么办
git bashh提示错误：
ERROR Script load failed: themes\diamond\scripts\helpers\hexo-html-truncate.js
Error: Cannot find module 'lodash.assignin'

**Comment by fool-cats** [comment]
已经解决了

**Comment by TriDiamond** [comment]
@fool-cats 谢谢你的支持！

**Comment by thejtf** [comment]
请问大佬们如何解决的，我也遇到了这个问题。

**Comment by thejtf** [comment]
> 请问我部署完后博客全白屏的，不是404要怎么办
> git bashh提示错误：
> ERROR Script load failed: themes\diamond\scripts\helpers\hexo-html-truncate.js
> Error: Cannot find module 'lodash.assignin'

请问大佬如何解决的，我也遇到了这个问题。
