### ISSUE TITLE
can support use KaTeX to render math equations.

### ISSUE THREAD

**Issue by zenwan** [TriDiamond/hexo-theme-obsidian#5]
Thank you very much for your work. This theme is perfect. Unfortunately, it doesn't support math  formulas.  
> https://katex.org/

**Comment by TriDiamond** [comment]
I will add this support in the next version. I should be able to have the time this weekend. Thanks for your feedback and suggestions!

**Comment by TriDiamond** [comment]
@zenwan Support had being added in Version [1.4.3](https://github.com/TriDiamond/hexo-theme-obsidian/releases/tag/v1.4.3)

Update your local theme and enjoy!
