### ISSUE TITLE
主页的标语被背景图片部分遮挡

### ISSUE THREAD

**Issue by Billtec** [TriDiamond/hexo-theme-obsidian#57]
如下图，遮挡的部分是随着背景图片渐显的过程逐渐被挡住的，有一个过程，我浏览器的缩放设置是100%没调过，感觉似乎跟窗口大小有关，看是否可以通过什么方法调整下，比如调整下背景图片的z-index属性，让其在标语div层下面？
![image](https://user-images.githubusercontent.com/13103365/73200088-1654fd80-4171-11ea-83be-050722ce53fc.png)

**Comment by 13slie** [comment]
这个问题前面的issue有人提到过，注释掉一行代码就好了
即`css\obsidian.styl`文件中的
```
#screen {
  z-index: 1;
  position: relative;
  background: #100e17;
  border-bottom-right-radius: 200px;

  .cover {
      /* position: absolute; */
    top: 0;
    left: 30%;
    width: 1200px;
    height: 800px;
    background-size: cover;
    background-repeat: no-repeat;
    opacity: 0.85;
  }
}
```
或者不注释代码，修改height的值为600px也行，我是这么改的，谷歌火狐Edge显示都是正常的。

**Comment by Billtec** [comment]
> 这个问题前面的issue有人提到过，注释掉一行代码就好了
> 即`css\obsidian.styl`文件中的
> 
> ```
> #screen {
>   z-index: 1;
>   position: relative;
>   background: #100e17;
>   border-bottom-right-radius: 200px;
> 
>   .cover {
>       /* position: absolute; */
>     top: 0;
>     left: 30%;
>     width: 1200px;
>     height: 800px;
>     background-size: cover;
>     background-repeat: no-repeat;
>     opacity: 0.85;
>   }
> }
> ```
> 
> 或者不注释代码，修改height的值为600px也行，我是这么改的，谷歌火狐Edge显示都是正常的。

**Comment by Billtec** [comment]
> 这个问题前面的issue有人提到过，注释掉一行代码就好了
> 即`css\obsidian.styl`文件中的
> 
> ```
> #screen {
>   z-index: 1;
>   position: relative;
>   background: #100e17;
>   border-bottom-right-radius: 200px;
> 
>   .cover {
>       /* position: absolute; */
>     top: 0;
>     left: 30%;
>     width: 1200px;
>     height: 800px;
>     background-size: cover;
>     background-repeat: no-repeat;
>     opacity: 0.85;
>   }
> }
> ```
> 
> 或者不注释代码，修改height的值为600px也行，我是这么改的，谷歌火狐Edge显示都是正常的。

注释掉 `position: absolute;` 会导致原来对齐好的背景图片变成左对齐了。height改为600px在我这里显示仍有一小部分会被遮挡，可能跟浏览器和屏幕分辨率有关，不一定适合所有人
