### ISSUE TITLE
您好！使用您的主题有一些问题请求解决

### ISSUE THREAD

**Issue by Fa1c0nSec** [TriDiamond/hexo-theme-obsidian#58]
您好，非常喜欢你的主题！已Star！
主题非常漂亮，有几个问题希望能解决一下：
1. CodeMirror在Chrome浏览器/Safari浏览器测试中，重复多次刷新会导致代码区域CodeMirror失效，请问问题是？
2. 对于较长的单篇博客，打开页面后CPU占用高达247%，页面运行缓慢和卡顿，Chrome80浏览器，Mac。
3.sharejs好像并不能使用？没有开发完成？
4.gitalk在PAC模式翻墙下的avatar不能显示，需全局翻墙才能正常显示，是否可以通过缓存机制解决？
5.以后是否会加入友情链接页面的开发？
6.音乐是否可以增加列表并选择多首歌曲播放？每次页面访问都加载默认的mp3，FTTB时间过长，是否可以异步加载？
7.第一篇博客下方的标语与博客内容的距离不定，文章长度稍长，会与文章过近，除了调整文章长度外，还有其他方法吗？
8.（建议）是否可以在_config.yml中增加渐变颜色设置选项，文字渐变色可根据图片动态改变？
谢谢🙏。

**Comment by AlphaHinex** [comment]
> 对于较长的单篇博客，打开页面后CPU占用高达247%，页面运行缓慢和卡顿，Chrome80浏览器，Mac。

可以看下 https://alphahinex.github.io/2020/04/03/css3-animation-cpu-usage-issue/
