### ISSUE TITLE
文章插入图片失败问题

### ISSUE THREAD

**Issue by lin-bin** [TriDiamond/hexo-theme-obsidian#59]
我按照网上的方法插入的图片，但是在生成网页后，他会在我的请求图片路径下自动加了一个路径，
比如：
   正确路径： https://lin-bin.github.io/myBlog/1.png
   实际路径： https://lin-bin.github.io/myBlog/.io//1.png
他会在中间生成一个 /.io/，这种问题怎么解决啊

我插入图片的方式：
1 把主页配置文件_config.yml 里的post_asset_folder:这个选项设置为true

2 在你的hexo目录下执行这样一句话npm install hexo-asset-image --save，这是下载安装一个可以上传本地图片的插件，来自dalao：dalao的git

3 等待一小段时间后，再运行hexo n "xxxx"来生成md博文时，/source/_posts文件夹内除了xxxx.md文件还有一个同名的文件夹

4 最后在xxxx.md中想引入图片时，先把图片复制到xxxx这个文件夹中，然后只需要在xxxx.md中按照markdown的格式引入图片：

![你想输入的替代文字](xxxx/图片名.jpg)

**Comment by TriDiamond** [comment]
这个是插件的问题哦，谢谢你的支持哈。
