### ISSUE TITLE
MathJax显示问题

### ISSUE THREAD

**Issue by hhhhhhhhjk** [TriDiamond/hexo-theme-obsidian#60]
你好，我在使用主题的过程中发现MathJax存在显示重复的问题：

`\frac{公式1}{公式2}`代码的显示效果为下图：

![批注 2020-02-01 120220](https://user-images.githubusercontent.com/54252549/73586620-d97b6480-44ea-11ea-8c40-f9d5b4ea1411.png)

请问有没有解决的办法呢，谢谢

**Comment by TriDiamond** [comment]
这个我可能要先排查一下了。不过我在重构这个主题了。

**Comment by zenwan** [comment]
> 这个我可能要先排查一下了。不过我在重构这个主题了。

MathJax 在markdown中存在部分渲染问题，可以考虑用KaTex 代替
https://katex.org/

**Comment by hhhhhhhhjk** [comment]
> 这个我可能要先排查一下了。不过我在重构这个主题了。

你好，我已经解决了，我把后面那一段文字的的style加了一个display:none，显示上基本没有影响。
