### ISSUE TITLE
刷新界面主题样式失效

### ISSUE THREAD

**Issue by InkosiZhong** [TriDiamond/hexo-theme-obsidian#62]
当我刷新页面之后，主题样式就消失了，只有重新输入主页网址重新进入文章样式才会恢复。请问是什么原因呢？
![Screenshot_20200211-233551_Chrome](https://user-images.githubusercontent.com/37005935/74252821-26e8a480-4d29-11ea-9e16-1a438b283a2f.png)
![Screenshot_20200211-234928_TIM](https://user-images.githubusercontent.com/37005935/74252833-2a7c2b80-4d29-11ea-87ba-db0caf929266.png)

**Comment by yansheng836** [comment]
网速可还行？如果是直接访问github pages有可能是墙的原因……

**Comment by InkosiZhong** [comment]
> 网速可还行？如果是直接访问github pages有可能是墙的原因……

前段时间尝试把它挂到阿里云上，目前在备案，等备案完进一步测试
