### ISSUE TITLE
页面会闪烁

### ISSUE THREAD

**Issue by RedTeamWing** [TriDiamond/hexo-theme-obsidian#66]
部署以后,和你的一样,右边一直在闪烁.
![image](https://user-images.githubusercontent.com/25416365/75226936-2f8cb080-57e8-11ea-8b85-dce227f38633.png)

**Comment by Sandy-Ding-Airwallex** [comment]
我也遇到闪烁问题, 手机端博客内容页, 标题图片背景那块初次加载背景会闪烁, 过一会再看就好了, [地址](sandy-ding.github.io)

**Comment by TriDiamond** [comment]
你们用的是什么浏览器呢？

**Comment by Sandy-Ding-Airwallex** [comment]
> 你们用的是什么浏览器呢？

我苹果手机端的safari和chrome都这样

**Comment by TriDiamond** [comment]
@Sandy-Ding-Airwallex 我看你的截图不是手机端的，是不是PC和手机都是这样呢？PC是用什么浏览器呢？

**Comment by Sandy-Ding-Airwallex** [comment]
> @Sandy-Ding-Airwallex 我看你的截图不是手机端的，是不是PC和手机都是这样呢？PC是用什么浏览器呢？

我PC都没问题, 就移动端的初次加载有问题

![IMG_3608](https://user-images.githubusercontent.com/62982596/87752382-d1ae4300-c832-11ea-9093-9c333326e6d0.PNG)

**Comment by TriDiamond** [comment]
Safari浏览器是有兼容问题，这个问题有另外一个Issue有相同的。 #79 #69 
到时候我一起解决掉哈。

**Comment by TriDiamond** [comment]
#
Duplicate of #69

**Comment by TriDiamond** [comment]
Duplicate of #69
