### ISSUE TITLE
代码块儿怎么显示黑色高亮？

### ISSUE THREAD

**Issue by rogerogerogeroger** [TriDiamond/hexo-theme-obsidian#70]
Hello，TriDiamond，您的主题很赞，不过添加主题后，发现代码块儿无法像您博客中一样黑色高亮显示，是需要做额外的配置吗？

**Comment by TriDiamond** [comment]
感谢你的支持！这个问题可以查看文档的这里哦。https://github.com/TriDiamond/hexo-theme-obsidian/blob/master/README_CN.md#%E4%BB%A3%E7%A0%81%E5%9D%97%E6%A0%B7%E5%BC%8F

**Comment by rogerogerogeroger** [comment]
谢谢！！ 刚才从你文档得到解决方案，回来就看到您的回复了！！ 再次感谢：）
