### ISSUE TITLE
添加可选显示的总访问量和总访客数

### ISSUE THREAD

**Issue by zjxjwxk** [TriDiamond/hexo-theme-obsidian#71]
您好，该主题是否有在页面最下方显示总访问量和总访客数的功能？使用Valine貌似只有单文章统计量，能否同时使用busuanzi的总访问量和Valine的评论系统？

**Comment by zjxjwxk** [comment]
自问自答：自测同时打开 busuanzi 和 Valine 貌似可以。
在 layout/layout.ejs  中 id 为 copyright 的 p 标签下方添加以下代码即可（来自不蒜子 
  http://ibruce.info/2015/04/04/busuanzi/）：
```HTML
<br>
本站总访问量 <span id="busuanzi_value_site_pv"></span> 次&nbsp;&nbsp;|&nbsp;&nbsp;本站访客数 <span id="busuanzi_value_site_uv"></span> 人
```
效果如下：

自问自答：自测同时打开 busuanzi 和 Valine 貌似可以。
在 layout/layout.ejs  中 id 为 copyright 的 p 标签下方添加以下代码即可（来自不蒜子 
  http://ibruce.info/2015/04/04/busuanzi/）：
```HTML
<br>
本站总访问量 <span id="busuanzi_value_site_pv"></span> 次&nbsp;&nbsp;|&nbsp;&nbsp;本站访客数 <span id="busuanzi_value_site_uv"></span> 人
```
效果如下：

![image](https://user-images.githubusercontent.com/32932726/76489703-3102dd80-6464-11ea-902b-bc3a5680990a.png)


（个人解决方法，期待作者进一步优化）

**Comment by TriDiamond** [comment]
其实总访问量是busuanzi的，Valine是没有提供这个统计的。😎😎😎

**Comment by JaydenChang** [comment]
> 自问自答：自测同时打开 busuanzi 和 Valine 貌似可以。
> 在 layout/layout.ejs 中 id 为 copyright 的 p 标签下方添加以下代码即可（来自不蒜子
> [http://ibruce.info/2015/04/04/busuanzi/）：](http://ibruce.info/2015/04/04/busuanzi/%EF%BC%89%EF%BC%9A)
> 
> ```
> <br>
> 本站总访问量 <span id="busuanzi_value_site_pv"></span> 次&nbsp;&nbsp;|&nbsp;&nbsp;本站访客数 <span id="busuanzi_value_site_uv"></span> 人
> ```
> 
> 效果如下：
> 
> ![image](https://user-images.githubusercontent.com/32932726/76489703-3102dd80-6464-11ea-902b-bc3a5680990a.png)
> 
> （个人解决方法，期待作者进一步优化）

老哥，你的这个方法确实可以，不过每次访问量都是+2，感觉有点不真实[Doge]
