### ISSUE TITLE
为啥我用官方主题是可以的，用您的后，GitHub上只有框架，没有代码，我哪里弄错了呢？

### ISSUE THREAD

**Issue by 1576946** [TriDiamond/hexo-theme-obsidian#73]

**Comment by TriDiamond** [comment]
你截图一下你的文件目录来看一下。

**Comment by 1576946** [comment]
![image](https://user-images.githubusercontent.com/38090814/78777632-76b3b700-79cc-11ea-8494-23bb77bc8108.png)

**Comment by 1576946** [comment]
github上目录
![image](https://user-images.githubusercontent.com/38090814/78777802-c7c3ab00-79cc-11ea-9558-b25a0b519f01.png)

**Comment by 1576946** [comment]
我使用的是阿里云主机

**Comment by yansheng836** [comment]
我觉得不是这个主题的问题，想问两个问题：

1. 第一次部署hexo，使用默认主题，本地测试行吗？
2. 上传到github上，使用github page，如何？<https://1576946.github.io/>

**Comment by 1576946** [comment]
嗯嗯 默认主题是可以的  
在 github 上 也可以 就是用的github page ，但是用这个主题后不行了  我也不知道为啥

**Comment by 1576946** [comment]
用next 也可以

**Comment by yansheng836** [comment]
那换用该主题后，本地测试怎么样？截个图

**Comment by 1576946** [comment]
空白

**Comment by 1576946** [comment]
感觉 github上 点开哪些代码文件都是空白的

**Comment by yansheng836** [comment]
额，怎么就这么固执呢？:rofl:老是说github，你上线前不用本地测试的吗？本地都没用，github上就可以？

配置贴一下？

**Comment by 1576946** [comment]
我的在阿里云上  ，测试的时候在直接输入ip 但是还是没用，是无法访问 ，我开启了访问端口访问权的

**Comment by 1576946** [comment]
hexo 下的配置 ，就加了最后面的几行

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/ 
         
# Site    
title: Hexo
subtitle: ''
description: ''
keywords:    
author: John Doe
language: en
timezone: ''
    
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: landscape
theme: obsibian
#theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:1576946/1576946.github.io.git
  branch: master

search:
  path: search.xml
  field: post
  content: true

**Comment by 1576946** [comment]
主题的配置都没改

**Comment by EmptyDreams** [comment]
你在本地用hexo s测试一下试试
