### ISSUE TITLE
请问网站的logo文字在哪里生成？

### ISSUE THREAD

**Issue by Flexiston** [TriDiamond/hexo-theme-obsidian#77]
网站的logo文字在哪里生成？

**Comment by AmosWang0626** [comment]
logo是个图片 `obsidian/source/img/logo.png`

**Comment by Flexiston** [comment]
那这个图片在哪里生成？

**Comment by AmosWang0626** [comment]
图片应该不是生成的。可以找一个图片、或者自己做一个图片，然后把对应的 `logo.png` 替换掉。
在线PS [在线PS](https://ps.gaoding.com/)

**Comment by Flexiston** [comment]
这个在线PS怎么导出呢

**Comment by AmosWang0626** [comment]
![image](https://user-images.githubusercontent.com/22915375/77820607-7be84a80-711e-11ea-925a-e4246ad86a9a.png)

**Comment by Flexiston** [comment]
谢谢

**Comment by Flexiston** [comment]
点击`导出为 PNG`后没反应，`方式1`也没反应

**Comment by Flexiston** [comment]
现在解决了，我用edge就可以下载了
