### ISSUE TITLE
页面样式问题

### ISSUE THREAD

**Issue by Sicmatr1x** [TriDiamond/hexo-theme-obsidian#8]
1. markdown里面的链接在主页缩略中显示为蓝色
2. markdown里面的带链接的标题在文章页面若光标悬停则会导致其消失
3. markdown里面的标题长度过长会超出右侧目录边框

**Comment by TriDiamond** [comment]
这些问题我先排查一下，在下个版本统一修复。

**Comment by TriDiamond** [comment]
已经在版本[`v1.3.4`](https://github.com/TriDiamond/hexo-theme-obsidian/releases/tag/v1.3.4)修复了以上问题。谢谢反馈！
