### ISSUE TITLE
初学者更换HEXO主题后页面一片空白是为什么？

### ISSUE THREAD

**Issue by twomoney** [TriDiamond/hexo-theme-obsidian#82]
第一次用github
第一次用github page
第一次用Hexo
第一次更换obsidian主题
然后页面就一片空白了，虽然感觉不是主题的原因，因为页面title都没有，但是我也不知道去哪里问相关的问题，有没有大佬帮忙分析下或者解决下。

拜谢！

**Comment by bwangll** [comment]
本地测试一下，终端会有报错信息

**Comment by yansheng836** [comment]
<https://shaomail.com/> 这不是正常吗？但是好型不是这个主题的

**Comment by ltxman** [comment]
我也是，更换主题后，网页直接一片空白，什么都没有了
这是本地测试的报错信息：
希望作者大大或大佬帮忙解决下，谢谢！
ERROR Script load failed: themes\obsidian\scripts\helpers\hexo-html-truncate.js
Error: Cannot find module 'lodash.assignin'
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\api\attributes.js
Error: Cannot find module 'css-select'
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\api\manipulation.js
Error: Cannot find module 'css-select'
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\static.js
Error: Cannot find module 'css-select'
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\static.js
Error: Cannot find module 'css-select'
ERROR Script load failed: themes\obsidian\scripts\libs\cheerio\static.js
Error: Cannot find module 'css-select'

**Comment by twomoney** [comment]
> <https://shaomail.com/> 这不是正常吗？但是好像不是这个主题的

是的，当时提问之后，又尝试了几次，然后加QQ群也没有很快通过，我就先换了个主题，换了以后就没出问题了。

**Comment by mkdir700** [comment]
也遇到了这个问题，查看文章详情，是可以访问的
主页的`index.html`文件是空白的，所以访问首页是空的。
暂时没找到原因

**Comment by mkdir700** [comment]
找到原因了， 模块缺失的问题
详见 #40  和  #97

**Comment by TriDiamond** [comment]
我已经在说明文档中加入了这个步骤了。谢谢大家支持！
