### ISSUE TITLE
这个主题有使用教程吗？

### ISSUE THREAD

**Issue by EmptyDreams** [TriDiamond/hexo-theme-obsidian#84]
hexo刚入坑不久，只是对MD比较了解，看到这个主题感觉非常炫酷，但是页面右上角那几个链接怎么设置页面？它提示我“Cannot GET /categories/”。
我怎么做才能做出作者这样子的效果？

**Comment by yansheng836** [comment]
不是有使用教程吗？<https://github.com/TriDiamond/hexo-theme-obsidian/blob/master/README_CN.md>

如果点击没效果，应该是没有新建页面，新建一个就好了：
```shell
hexo new page categories
```
