### ISSUE TITLE
手机端浏览器兼容问题

### ISSUE THREAD

**Issue by EmptyDreams** [TriDiamond/hexo-theme-obsidian#89]
经过测试多个浏览器无法打开这个主题的博客，已知的有：X浏览器，via，凤凰浏览器三种浏览器无法打开。
现象是虽然加载出了页面但是会一直卡在最开始的加载页面。

**Comment by TriDiamond** [comment]
这些浏览器没有听说过。用的是什么内核？

**Comment by EmptyDreams** [comment]
> 这些浏览器没有听说过。用的是什么内核？

用的是系统自带的内核
我的系统是安卓5.0，手机SM-G900H
这个情况不止在我的手机上出现，在朋友的小米手机上同样也有

**Comment by hui-shao** [comment]
> > 这些浏览器没有听说过。用的是什么内核？
> 
> 用的是系统自带的内核
> 我的系统是安卓5.0，手机SM-G900H
> 这个情况不止在我的手机上出现，在朋友的小米手机上同样也有

我目前暂时没遇到这个情况。说下我的情况 ：
小米6  +  Via浏览器 ，可以正常打开

**Comment by EmptyDreams** [comment]
可能是手机问题吧，浏览器的作者也能打开
---原始邮件---
发件人:"Mr. Hui"<notifications@github.com>
发送时间:2020年4月28日 星期二 下午3:28
收件人:"TriDiamond/hexo-theme-obsidian"<hexo-theme-obsidian@noreply.github.com>
抄送:"空梦"<minedreams@qq.com>;"Author"<author@noreply.github.com>
主题:Re: [TriDiamond/hexo-theme-obsidian] 手机端浏览器兼容问题 (#89)



这些浏览器没有听说过。用的是什么内核？

用的是系统自带的内核
我的系统是安卓5.0，手机SM-G900H
这个情况不止在我的手机上出现，在朋友的小米手机上同样也有

我目前暂时没遇到这个情况。说下我的情况 ：
小米6  +  Via浏览器 ，可以正常打开

&mdash;
