### ISSUE TITLE
iconfont 如何更新或者添加？

### ISSUE THREAD

**Issue by jjjjyx** [TriDiamond/hexo-theme-obsidian#9]
<%- css(['//at.alicdn.com/t/font_1429596_nuy6s3evgdk.css'])%> 

直接引用了一個iconfont ，但是我想添加一些貌似有點困難
A direct reference to an iconfont css was made, but I think it seems a little difficult to add some.

**Comment by jjjjyx** [comment]
如何克隆大佬的iconfont 項目

**Comment by TriDiamond** [comment]
> 如何克隆大佬的iconfont 項目

这样吧兄弟，我明天去公司后，把项目下载下来放到项目文件夹里面。

**Comment by TriDiamond** [comment]
Duplicate of #34
